##########
# collectionbuilder-sheets
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-sheets
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-sheets

##########
# SITE SETTINGS
#
# title of site appears in banner
title: CollectionBuilder-Sheets
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: a template for creating simple digital exhibits
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Explore the story of San Francisco—a city defined by resilience, creativity, and change. From its founding in 1776 and the Gold Rush boom of 1849, to the rise of tech innovation in Silicon Valley, San Francisco has evolved into a global symbol of opportunity. Its neighborhoods, from Chinatown to the Mission District, reflect a rich blend of cultures that shape the city’s art, cuisine, and music. Follow our interactive timeline to trace key moments like the 1906 earthquake, the Summer of Love in 1967, and the dot-com era, and discover how San Francisco’s diversity and forward-thinking spirit continue to influence both American culture and the world."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Carson Kotula

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection 
# This will be the full URL to your CSV file or relative path + filename of CSV in this repository 
# e.g. relative path "/assets/demo-metadata.csv"
# e.g. published google sheet "https://docs.google.com/spreadsheets/d/e/2PACX-1vSn7AA-cbsXT3_nNUGftc1ab-CKXOJHMQCIENeR9NHElbyI9_qA99o0-HNZdG04v-M2_N21bUe_krQQ/pub?output=csv"
# e.g. on GitHub use the raw link "https://raw.githubusercontent.com/CollectionBuilder/collectionbuilder-sample-data/main/psychiana_cbdemo_gh.csv"
metadata-csv: https://docs.google.com/spreadsheets/d/e/2PACX-1vRWq4YMn-V62hEWBFmHhxM7ugRvf9EywpeuR22nmYiJr9XQBo8oi_vtRTRFC0D6NIL6wuxEjPFuSv06/pub?output=csv

##########
# Site/Organization Branding 
# 
# Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# dev mode turns on ability to change metadata
development-mode: true
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
